<?
print( "<table summary=\"\" width='100%'>\n" );
print( "	<tr>\n" );
print( "		<td valign='top' width='80%'>" );
print( "			<p>\n" );
print( "						 <b>Nome dello script:</b>\n" );
print( "						 <input type='text' size=40 name='fNomeScript'>\n" );
print( "			</p>\n" );
print( "			<p><b>Testo dello script:</b></p>\n" );
print( "			<p>\n" );
print( "				 <textarea class=\"script\" name=\"fTestoScript\" rows=15 cols=120>inserire il testo dello script</textarea>\n" );
print( "			</p>\n" );
print( "</td>\n" );
print( "</tr>\n" );
print( "</table>\n" );

?>
