<?
print( "									 <div class=titolo>CARATTERISTICHE</div>\n" );
print( "							 		 <table>\n" );
print( "          						  <tr>\n" );
print( "          						 			<td>Pollici</td>\n" );
print( "          								 <td>\n" );
print( "          										 <input type=\"text\" size=4 name=\"pollici\" value=\"$dati->pollici\">\n" );
print( "          								 </td>\n" );
print( "          						 </tr>\n" );
print( "          						 <tr>\n" );
print( "          								 <td>Tipo:</td>\n" );
print( "													 <td><input type=\"text\" size=7 name=\"tipomon\" value=\"$dati->tipomon\"></td>\n" );
print( "          						 </tr>\n" );
print( "          						 <tr>\n" );
print( "								 					 <td>Motherboard:</td> \n" );
print( "            							 <td><input type=\"text\" name=\"madre\" value=\"$dati->madre\"></td>\n" );
print( "          						 </tr>\n" );
print( "          						 <tr>\n" );
print( "								 					 <td>CPU:</td> \n" );
print( "            							 <td><input type=\"text\" name=\"CPU\" value=\"$dati->CPU\"></td>\n" );
print( "          						 </tr>\n" );
print( "          						 <tr>\n" );
print( "            						 	 <td>RAM:</td> \n" );
print( "            							 <td><input type=\"text\" name=\"RAM\" value=\"$dati->RAM\">Mb</td>\n" );
print( "          						 </tr>\n" );
print( "          						 <tr>\n" );
print( "            						 	 <td>HD:</td> \n" );
print( "            							 <td><input type=\"text\" name=\"HD\" value=\"$dati->HD\"></td>\n" );
print( "          						 </tr>\n" );
print( "						 					 <tr>" );
print( "						 		 			 		 <td>\n" );
print( "													 Lettore ottico 1: tipo\n" );
print( "													 </td>\n" );
print( "						 		 					 <td>\n" );
print( "						 		 					 <input type=\"text\" name=\"lettore1\" value=\"$dati->lettore1\">\n" );
print( "													 </td>\n" );
print( "						 					 </tr>\n" );
print( "						 					 <tr>\n" );
print( "						 		 			 		 <td>\n" );
print( "													 Lettore ottico 2: tipo\n" );
print( "													 </td>\n" );
print( "						 		 					 <td>\n" );
print( "													 <input type=\"text\" name=\"lettore2\" value=\"$dati->lettore2\">\n" );
print( "													 </td>\n" );
print( "          						 </tr>\n" );
print( "          						 <tr>\n" );
print( "						 		 			 		 <td>Scheda video</td>\n" );
print( "						 		 					 <td><input type=\"text\" name=\"skvideo\" value=\"$dati->skvideo\"></td>\n" );
print( "          						 </tr>\n" );
print( "          						 <tr>\n" );
print( "						 		 			 		 <td>Sezione audio</td>\n" );
print( "						 		 					 <td><input type=\"text\" name=\"audio\" value=\"$dati->audio\"></td>\n" );
print( "						 					 </tr>\n" );
print( "									 </table>\n" );
?>