<?
print( "										 <div class=titolo>IMPOSTAZIONI DI RETE</div>		 " );
print( "								 		 <table>\n" );
print( "          						 <tr>\n" );
print( "								 					 <td>\n" );
print( "													 Rete 1: Tipo :  \n" );
print( "								 					 </td>\n" );
print( "													 <td> \n" );
print( "													 <input type=\"text\" name=\"skrete1\" value=\"$dati->skrete1\">\n" );
print( "								 					 </td>\n" );
print( "								 					 <td>\n" );
print( "													 Rete 2: Tipo :  \n" );
print( "								 					 </td>\n" );
print( "													 <td> \n" );
print( "													 <input type=\"text\" name=\"skrete2\" value=\"$dati->skrete2\">\n" );
print( "								 					 </td>\n" );
print( "						 					 </tr>\n" );
print( "          						 <tr>\n" );
print( "								 					 <td>\n" );
print( "													 Rete 1: IP Address :\n" );
print( "								 					 </td>\n" );
print( "								 					 <td>\n" );
print( "								 					 <input type=\"text\" size=15 maxlenght=\"15\" name=\"IP\" value=\"".NormalizeIP($dati->IPAddress)."\">\n" );
print( "								 					 </td>\n" );
print( "								 					 <td>\n" );
print( "													 Rete 2: IP Address :\n" );
print( "								 					 </td>\n" );
print( "								 					 <td>\n" );
print( "								 					 <input type=\"text\" size=15 maxlenght=\"15\" name=\"IP2\" value=\"".NormalizeIP($dati->IPAddress2)."\">\n" );
print( "								 					 </td>\n" );
print( "						 					 </tr>\n" );
print( "          						 <tr>\n" );
print( "								 					 <td>\n" );
print( "													 Rete 1: IP NetMask : \n" );
print( "													 </td>\n" );
print( "								 					 <td>\n" );
print( "								 					 <input type=\"text\" size=15 maxlenght=\"15\" name=\"NM\" value=\"".NormalizeIP($dati->Netmask)."\">\n" );
print( "								 					 </td>\n" );
print( "								 					 <td>\n" );
print( "													 Rete 2: IP NetMask : \n" );
print( "													 </td>\n" );
print( "								 					 <td>\n" );
print( "								 					 <input type=\"text\" size=15 maxlenght=\"15\" name=\"NM2\" value=\"".NormalizeIP($dati->Netmask2)."\">\n" );
print( "								 					 </td>\n" );
print( "						 					 </tr>\n" );
print( "          						 <tr>\n" );
print( "								 					 <td>\n" );
print( "								 					 Rete 1: Gateway : \n" );
print( "								 					 </td>\n" );
print( "								 					 <td>\n" );
print( "								 					 <input type=\"text\" size=15 maxlenght=\"15\" name=\"GW1\" value=\"".NormalizeIP($dati->Gateway)."\">\n" );
print( "								 					 </td>\n" );
print( "								 					 <td>\n" );
print( "													 Rete 2: Gateway : \n" );
print( "													 </td>\n" );
print( "								 					 <td>\n" );
print( "								 					 <input type=\"text\" size=15 maxlenght=\"15\" name=\"GW2\" value=\"".NormalizeIP($dati->Gateway2)."\">\n" );
print( "													 </td>\n" );
print( "						 					 </tr>\n" );
print( "          						 <tr>\n" );
print( "								 					 <td colspan='4'>\n" );
print( "								 					 <hr>\n" );
print( "													 </td>\n" );
print( "						 					 </tr>\n" );
print( "          						 <tr>\n" );
print( "								 					 <td>\n" );
print( "													 Gruppo di lavoro o Dominio : \n" );
print( "													 </td>\n" );
print( "								 					 <td>\n" );
print( "                              <select name=\"GroupType\">\n" );
$sel=$dati->TipoGruppo==""?"selected":"";
print( "                                <option value=\"\" $sel>ALTRO/N.A.</option>\n" );
$sel=$dati->TipoGruppo=="W"?"selected":"";
print( "                                <option value=\"W\" $sel>WORKGROUP</option>\n" );
$sel=$dati->TipoGruppo=="D"?"selected":"";
print( "                                <option value=\"D\" $sel>DOMINIO</option>\n" );
print( "                              </select>\n" );
print( "								 					 </td>\n" );
print( "						 					 </tr>\n" );
print( "          						 <tr>\n" );
print( "								 					 <td>\n" );
print( "													 Nome Gruppo/dominio : \n" );
print( "													 </td>\n" );
print( "								 					 <td>\n" );
print( "								 					 <input type=\"text\" size=20 maxlenght=\"20\" name=\"GroupName\" value=\"$dati->NomeGruppo\">\n" );
print( "								 					 </td>\n" );
print( "						 					 </tr>\n" );
print( "          						 <tr>\n" );
print( "								 					 <td> ID di rete</td>\n" );
print( "          								 <td> \n" );
print( "          								 <input type=\"text\" size=20 maxlenght=32 value=\"$dati->IDrete\"name=\"NetID\">\n" );
print( "          								 </td>\n" );
print( "						 					 </tr>\n" );
print( "          						 <tr>\n" );
print( "								 					 <td colspan='4'>\n" );
print( "								 					 <hr>\n" );
print( "													 </td>\n" );
print( "						 					 </tr>\n" );
print( "          						 <tr>\n" );
print( "          						 		  <td>Password Amministrativa</td>\n" );
print( "          								  <td> \n" );
print( "          								 	<input type=\"text\" size=12 name=\"passwordAdmin\" value=\"$dati->AdminPWD\">\n" );
print( "          								  </td>\n" );
print( "          						 		  <td>Password VNC</td>\n" );
print( "          								  <td> \n" );
print( "          								 	<input type=\"text\" size=8 maxlenght=8 name=\"passwordVNC\" value=\"$dati->VNCPWD\">\n" );
print( "          								  </td>\n" );
print( "						 					 </tr>\n" );
print( "          						 <tr>\n" );
print( "								 					 <td>\n" );
print( "													 Default user name : \n" );
print( "													 </td>\n" );
print( "								 					 <td>\n" );
print( "								 					 <input type=\"text\" size=15 maxlenght=\"15\" name=\"nomeutente\" value=\"$dati->UserName\">\n" );
print( "													 </td>\n" );
print( "								 					 <td>\n" );
print( "													 Default password : \n" );
print( "													 </td>\n" );
print( "								 					 <td>\n" );
print( "								 					 <input type=\"text\" size=15 maxlenght=\"15\" name=\"pwutente\" value=\"$dati->UserPWD\">\n" );
print( "													 </td>\n" );
print( "						 					 </tr>\n" );
print( "								 		 </table>\n" );
?>
<script language="JavaScript" type="text/javascript">
<!--
	$(":input[name=IP]").mask("999.999.999.999").val('<?echo NormalizeIP($dati->IPAddress);?>');
	$(":input[name=IP2]").mask("999.999.999.999").val('<?echo NormalizeIP($dati->IPAddress2);?>');
	$(":input[name=NM]").mask("999.999.999.999").val('<?echo NormalizeIP($dati->Netmask);?>');
	$(":input[name=NM2]").mask("999.999.999.999").val('<?echo NormalizeIP($dati->Netmask2);?>');
	$(":input[name=GW1]").mask("999.999.999.999").val('<?echo NormalizeIP($dati->Gateway);?>');
	$(":input[name=GW2]").mask("999.999.999.999").val('<?echo NormalizeIP($dati->Gateway2);?>');
//-->
</script>
